### PR TITLE
Remove expected attributes from deleting session.

### LINKED ISSUE #10: Remove expected attributes from delete session
When using dynamodb sessions the delete options contain expected attributes:
https://github.com/aws/aws-sessionstore-dynamodb-ruby/blob/master/lib/aws/session_store/dynamo_db/locking/base.rb#L68
https://github.com/aws/aws-sessionstore-dynamodb-ruby/blob/master/lib/aws/session_store/dynamo_db/locking/base.rb#L146

These work fine when using the application, but cause our spec suite to fail as the delete operation could attempt to delete a session not in the database.  With expected attributes set it raises an error if the expected attributes are not within the database rather than failing silently.  

Is it necessary to keep expected attributes or could I submit a pull request to either remove them or make them optional?

### PR DESCRIPTION
**Pull request by JDutil**
Fixes #10

I would merge #9 first as that fixes the specs.  The failure here is currently on master branch.

### CODE REVIEW

**Comment by cjyclaire** [comment]
Hmm taking a second look at the diff, the `ServiceError` change looks good to me, yet for user agent diff and spec diff, may I ask are they causing trouble for you?

**Comment by JDutil** [comment]
@cjyclaire no they aren't and I'm not sure why they are in the diff. I tried updating this PR last night with latest work and noticed these unrelated diffs being included, and was too tired to work on fixing at the time.  I'll revisit this to clean up the diff. 

Also FYI I'm not sure that #15 was configured correctly because these commits didn't trigger any build, but maybe that's because this is an older PR? Perhaps I need to reopen a new one to get it to build once I clean up the diff?

**Comment by cjyclaire** [comment]
Hmm, weird, you can open a new one if it gets messy ; ) I'll take a look and merge it. Thanks!

**Comment by JDutil** [comment]
For some reason this PR doesn't even include the main fix anymore...

Essentially all I wanted to do was change:
```
# @return [Hash] Options for deleting session.
def delete_opts(sid)
     merge_all(table_opts(sid), expected_attributes(sid))
end
````

to

```
# @return [Hash] Options for deleting session.
def delete_opts(sid)
      table_opts(sid)
end
```

When deleting records there is no reason to ensure they have those expected_attributes we can just delete the record.

**Comment by JDutil** [comment]
Closing for now until I get a chance to fix up this PR as intended again.

**Pull request closed without merging**
